-- Pharmacy locations, batch/expiry control, medicine returns and traceable
-- inventory movements. Existing branch stock remains the aggregate balance.

CREATE TABLE `pharmacy_locations` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `locationType` VARCHAR(40) NOT NULL DEFAULT 'MAIN',
  `isDispensingLocation` BOOLEAN NOT NULL DEFAULT true,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `pharmacy_locations_branchId_code_key` (`branchId`, `code`),
  INDEX `pharmacy_locations_facilityId_branchId_isActive_idx` (`facilityId`, `branchId`, `isActive`),
  PRIMARY KEY (`id`),
  CONSTRAINT `pharmacy_locations_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pharmacy_locations_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `pharmacy_location_stocks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NOT NULL,
  `pharmacyLocationId` INTEGER NOT NULL,
  `medicineId` INTEGER NOT NULL,
  `branchStockId` INTEGER NULL,
  `stockQuantity` INTEGER NOT NULL DEFAULT 0,
  `reorderLevel` INTEGER NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `pharmacy_location_stocks_location_medicine_key` (`pharmacyLocationId`, `medicineId`),
  INDEX `pharmacy_location_stocks_facility_branch_active_idx` (`facilityId`, `branchId`, `isActive`),
  INDEX `pharmacy_location_stocks_medicineId_idx` (`medicineId`),
  INDEX `pharmacy_location_stocks_branchStockId_idx` (`branchStockId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `pharmacy_location_stocks_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pharmacy_location_stocks_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pharmacy_location_stocks_locationId_fkey` FOREIGN KEY (`pharmacyLocationId`) REFERENCES `pharmacy_locations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pharmacy_location_stocks_medicineId_fkey` FOREIGN KEY (`medicineId`) REFERENCES `medicines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `pharmacy_location_stocks_branchStockId_fkey` FOREIGN KEY (`branchStockId`) REFERENCES `branch_medicine_stocks`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `medicine_batches` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NOT NULL,
  `pharmacyLocationId` INTEGER NOT NULL,
  `medicineId` INTEGER NOT NULL,
  `branchStockId` INTEGER NULL,
  `batchNumber` VARCHAR(100) NOT NULL,
  `supplierName` VARCHAR(180) NULL,
  `manufacturerName` VARCHAR(180) NULL,
  `manufacturedAt` DATETIME(3) NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `expiresAt` DATETIME(3) NOT NULL,
  `quantityReceived` INTEGER NOT NULL,
  `quantityAvailable` INTEGER NOT NULL,
  `unitCost` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `statusCode` VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `medicine_batches_location_medicine_batch_key` (`pharmacyLocationId`, `medicineId`, `batchNumber`),
  INDEX `medicine_batches_facility_branch_expiry_idx` (`facilityId`, `branchId`, `expiresAt`),
  INDEX `medicine_batches_medicine_expiry_idx` (`medicineId`, `expiresAt`),
  INDEX `medicine_batches_status_expiry_idx` (`statusCode`, `expiresAt`),
  INDEX `medicine_batches_branchStockId_idx` (`branchStockId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `medicine_batches_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_batches_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_batches_locationId_fkey` FOREIGN KEY (`pharmacyLocationId`) REFERENCES `pharmacy_locations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_batches_medicineId_fkey` FOREIGN KEY (`medicineId`) REFERENCES `medicines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_batches_branchStockId_fkey` FOREIGN KEY (`branchStockId`) REFERENCES `branch_medicine_stocks`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `medicine_returns` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `returnNumber` VARCHAR(60) NOT NULL,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NOT NULL,
  `pharmacyLocationId` INTEGER NOT NULL,
  `patientId` INTEGER NOT NULL,
  `dispenseId` INTEGER NULL,
  `statusCode` VARCHAR(50) NOT NULL DEFAULT 'PENDING_INSPECTION',
  `returnReason` TEXT NOT NULL,
  `inspectionNotes` TEXT NULL,
  `receivedByStaffId` INTEGER NULL,
  `reviewedByStaffId` INTEGER NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `reviewedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `medicine_returns_returnNumber_key` (`returnNumber`),
  INDEX `medicine_returns_facility_branch_status_received_idx` (`facilityId`, `branchId`, `statusCode`, `receivedAt`),
  INDEX `medicine_returns_patientId_idx` (`patientId`),
  INDEX `medicine_returns_dispenseId_idx` (`dispenseId`),
  INDEX `medicine_returns_locationId_idx` (`pharmacyLocationId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `medicine_returns_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_locationId_fkey` FOREIGN KEY (`pharmacyLocationId`) REFERENCES `pharmacy_locations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_patientId_fkey` FOREIGN KEY (`patientId`) REFERENCES `patients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_dispenseId_fkey` FOREIGN KEY (`dispenseId`) REFERENCES `dispenses`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_receivedByStaffId_fkey` FOREIGN KEY (`receivedByStaffId`) REFERENCES `staff_members`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `medicine_returns_reviewedByStaffId_fkey` FOREIGN KEY (`reviewedByStaffId`) REFERENCES `staff_members`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `medicine_return_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `medicineReturnId` INTEGER NOT NULL,
  `dispenseItemId` INTEGER NULL,
  `medicineId` INTEGER NOT NULL,
  `medicineBatchId` INTEGER NULL,
  `quantityReturned` INTEGER NOT NULL,
  `conditionCode` VARCHAR(50) NOT NULL,
  `dispositionCode` VARCHAR(50) NULL,
  `dispositionReason` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `medicine_return_items_returnId_idx` (`medicineReturnId`),
  INDEX `medicine_return_items_dispenseItemId_idx` (`dispenseItemId`),
  INDEX `medicine_return_items_medicineId_idx` (`medicineId`),
  INDEX `medicine_return_items_batchId_idx` (`medicineBatchId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `medicine_return_items_returnId_fkey` FOREIGN KEY (`medicineReturnId`) REFERENCES `medicine_returns`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_return_items_dispenseItemId_fkey` FOREIGN KEY (`dispenseItemId`) REFERENCES `dispense_items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `medicine_return_items_medicineId_fkey` FOREIGN KEY (`medicineId`) REFERENCES `medicines`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `medicine_return_items_batchId_fkey` FOREIGN KEY (`medicineBatchId`) REFERENCES `medicine_batches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `pharmacy_stock_movements`
  ADD COLUMN `pharmacyLocationId` INTEGER NULL,
  ADD COLUMN `medicineBatchId` INTEGER NULL,
  ADD COLUMN `medicineReturnItemId` INTEGER NULL,
  ADD INDEX `pharmacy_stock_movements_locationId_idx` (`pharmacyLocationId`),
  ADD INDEX `pharmacy_stock_movements_batchId_idx` (`medicineBatchId`),
  ADD INDEX `pharmacy_stock_movements_returnItemId_idx` (`medicineReturnItemId`),
  ADD CONSTRAINT `pharmacy_stock_movements_locationId_fkey` FOREIGN KEY (`pharmacyLocationId`) REFERENCES `pharmacy_locations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `pharmacy_stock_movements_batchId_fkey` FOREIGN KEY (`medicineBatchId`) REFERENCES `medicine_batches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `pharmacy_stock_movements_returnItemId_fkey` FOREIGN KEY (`medicineReturnItemId`) REFERENCES `medicine_return_items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
