CREATE TABLE `insurance_payers` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facilityId` INTEGER NOT NULL,
  `code` VARCHAR(60) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `payerType` VARCHAR(40) NOT NULL DEFAULT 'PRIVATE',
  `integrationBaseUrl` VARCHAR(500) NULL,
  `eligibilityPath` VARCHAR(300) NULL,
  `claimSubmissionPath` VARCHAR(300) NULL,
  `authorizationCiphertext` TEXT NULL,
  `isActive` BOOLEAN NOT NULL DEFAULT true,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `insurance_payers_facilityId_code_key` (`facilityId`, `code`),
  INDEX `insurance_payers_facilityId_payerType_isActive_idx` (`facilityId`, `payerType`, `isActive`),
  PRIMARY KEY (`id`),
  CONSTRAINT `insurance_payers_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `patient_insurance_policies` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NULL,
  `patientId` INTEGER NOT NULL,
  `insurancePayerId` INTEGER NOT NULL,
  `policyNumber` VARCHAR(120) NOT NULL,
  `memberNumber` VARCHAR(120) NULL,
  `principalMemberName` VARCHAR(180) NULL,
  `relationshipToPrincipal` VARCHAR(60) NULL,
  `coverStartAt` DATETIME(3) NULL,
  `coverEndAt` DATETIME(3) NULL,
  `benefitLimit` DECIMAL(18, 2) NULL,
  `statusCode` VARCHAR(50) NOT NULL DEFAULT 'PENDING_VERIFICATION',
  `lastVerifiedAt` DATETIME(3) NULL,
  `verificationReference` VARCHAR(160) NULL,
  `verificationResponse` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `patient_insurance_policies_payer_policy_patient_key` (`insurancePayerId`, `policyNumber`, `patientId`),
  INDEX `patient_insurance_policies_scope_status_idx` (`facilityId`, `branchId`, `statusCode`),
  INDEX `patient_insurance_policies_patientId_idx` (`patientId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `patient_insurance_policies_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `patient_insurance_policies_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `patient_insurance_policies_patientId_fkey` FOREIGN KEY (`patientId`) REFERENCES `patients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `patient_insurance_policies_insurancePayerId_fkey` FOREIGN KEY (`insurancePayerId`) REFERENCES `insurance_payers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `private_insurance_claims` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `claimNumber` VARCHAR(70) NOT NULL,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NULL,
  `insurancePayerId` INTEGER NOT NULL,
  `patientInsurancePolicyId` INTEGER NOT NULL,
  `invoiceId` INTEGER NOT NULL,
  `statusCode` VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
  `claimedAmount` DECIMAL(18, 2) NOT NULL,
  `approvedAmount` DECIMAL(18, 2) NULL,
  `externalClaimId` VARCHAR(160) NULL,
  `submissionReference` VARCHAR(160) NULL,
  `submittedAt` DATETIME(3) NULL,
  `responsePayload` TEXT NULL,
  `rejectionReason` TEXT NULL,
  `createdByUserId` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `private_insurance_claims_claimNumber_key` (`claimNumber`),
  UNIQUE INDEX `private_insurance_claims_policy_invoice_key` (`patientInsurancePolicyId`, `invoiceId`),
  INDEX `private_insurance_claims_scope_status_created_idx` (`facilityId`, `branchId`, `statusCode`, `createdAt`),
  INDEX `private_insurance_claims_insurancePayerId_idx` (`insurancePayerId`),
  INDEX `private_insurance_claims_policyId_idx` (`patientInsurancePolicyId`),
  INDEX `private_insurance_claims_invoiceId_idx` (`invoiceId`),
  INDEX `private_insurance_claims_externalClaimId_idx` (`externalClaimId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `private_insurance_claims_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `private_insurance_claims_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `private_insurance_claims_insurancePayerId_fkey` FOREIGN KEY (`insurancePayerId`) REFERENCES `insurance_payers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `private_insurance_claims_policyId_fkey` FOREIGN KEY (`patientInsurancePolicyId`) REFERENCES `patient_insurance_policies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `private_insurance_claims_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `invoices`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
