import { apiFetch, API_BASE_URL } from "@/lib/api";

export interface BillingServiceItem {
  id: number;
  code: string;
  name: string;
  category?: string | null;
  defaultPrice: number;
  isActive: boolean;
}

export interface InvoiceItemRecord {
  id: number;
  invoiceId: number;
  billingServiceId?: number | null;
  description: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  statusCode: string;
  notes?: string | null;
  sourceModule?: string | null;
  sourceEntityType?: string | null;
  sourceEntityId?: string | null;
  isAutoGenerated?: boolean;
  isRemoved?: boolean;
  removedAt?: string | null;
  removedReason?: string | null;
  billingService?: {
    id: number;
    code: string;
    name: string;
    category?: string | null;
    defaultPrice: number;
  } | null;
  invoice?: InvoiceRecord;
  updatedBy?: {
    id: number;
    firstName?: string;
    lastName?: string;
    staffCode?: string;
  } | null;
}

export interface PaymentRecord {
  id: number;
  receiptNumber: string;
  amount: number;
  paymentMethod: string;
  statusCode: string;
  phoneNumber?: string | null;
  transactionRef?: string | null;
  mpesaReceiptNumber?: string | null;
  paidAt?: string | null;
  confirmedAt?: string | null;
  notes?: string | null;
  invoice?: InvoiceRecord;
  receivedBy?: {
    id: number;
    firstName?: string;
    lastName?: string;
    staffCode?: string;
  } | null;
}

export interface InvoiceRecord {
  id: number;
  invoiceNumber: string;
  statusCode: string;
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  notes?: string | null;
  issuedAt?: string;
  settledAt?: string | null;
  facilityId: number;
  branchId?: number | null;
  patientId: number;
  appointmentId?: number | null;
  consultationId?: number | null;
  admissionId?: number | null;
  createdByStaffId?: number | null;
  patient?: {
    id: number;
    patientNumber?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    gender?: string | null;
    phonePrimary?: string | null;
  } | null;
  facility?: {
    id: number;
    name?: string;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    website?: string | null;
    logoUrl?: string | null;
    mpesaPaybill?: string | null;
    mpesaTillNumber?: string | null;
    mpesaShortcode?: string | null;
  } | null;
  branch?: {
    id: number;
    name?: string;
  } | null;
  items?: InvoiceItemRecord[];
  payments?: PaymentRecord[];
}

export interface BillingDashboardRecord {
  counts: {
    totalInvoices: number;
    pendingInvoices: number;
    partiallyPaidInvoices: number;
    paidInvoices: number;
  };
  sums: {
    totalAmount: number;
    paidAmount: number;
    balanceAmount: number;
  };
}

export interface RevenueIntegrityRecord {
  summary: {
    exceptionCount: number;
    missingPriceCount: number;
    removedLineCount: number;
    autoGeneratedCount: number;
  };
  missingPriceItems: InvoiceItemRecord[];
  removedItems: InvoiceItemRecord[];
  exceptionItems: InvoiceItemRecord[];
}

export interface CashierCloseRecord {
  date: string;
  summary: {
    paymentCount: number;
    totalCollected: number;
    invoiceCount: number;
    invoiceTotal: number;
    removedLineCount: number;
    removedLineValue: number;
    paymentsByMethod: Record<string, number>;
  };
  payments: PaymentRecord[];
  invoicesIssued: InvoiceRecord[];
  removedItems: InvoiceItemRecord[];
}

export interface ServiceTariffRecord {
  id: number;
  code: string;
  name: string;
  category: string;
  facilityId: number;
  branchId?: number | null;
  billingServiceId?: number | null;
  labTestId?: number | null;
  wardId?: number | null;
  bedId?: number | null;
  unitPrice: number;
  isActive: boolean;
  notes?: string | null;
  facility?: {
    id: number;
    name?: string;
  } | null;
  branch?: {
    id: number;
    name?: string;
  } | null;
  billingService?: {
    id: number;
    name?: string;
    code?: string;
  } | null;
  labTest?: {
    id: number;
    testName?: string;
  } | null;
  ward?: {
    id: number;
    name?: string;
  } | null;
  bed?: {
    id: number;
    bedNumber?: string;
    bedLabel?: string | null;
  } | null;
}

export interface CreateServiceTariffPayload {
  code: string;
  name: string;
  category: string;
  facilityId: number;
  branchId?: number | null;
  billingServiceId?: number | null;
  labTestId?: number | null;
  wardId?: number | null;
  bedId?: number | null;
  unitPrice: number;
  isActive?: boolean;
  notes?: string;
}

export interface UpdateInvoiceItemPayload {
  description?: string;
  quantity?: number;
  unitPrice?: number;
  notes?: string;
  statusCode?: string;
  updatedByStaffId?: number;
}

export interface RemoveInvoiceItemPayload {
  reason: string;
}

export interface CreateCashPaymentPayload {
  receiptNumber: string;
  invoiceId: number;
  amount: number;
  notes?: string;
  receivedByStaffId?: number;
}

export interface CreateMpesaPaymentRequestPayload {
  receiptNumber: string;
  invoiceId: number;
  amount: number;
  phoneNumber: string;
  notes?: string;
  receivedByStaffId?: number;
}

export async function getBillingDashboard() {
  return apiFetch<BillingDashboardRecord>("/billing/dashboard", {
    method: "GET",
  });
}

export async function getRevenueIntegrity() {
  return apiFetch<RevenueIntegrityRecord>("/billing/revenue-integrity", {
    method: "GET",
  });
}

export async function getCashierClose(date?: string) {
  const query = date ? `?date=${encodeURIComponent(date)}` : "";
  return apiFetch<CashierCloseRecord>(`/billing/cashier-close${query}`, {
    method: "GET",
  });
}

export async function getInvoices() {
  return apiFetch<InvoiceRecord[]>("/billing/invoices", {
    method: "GET",
  });
}

export async function getInvoiceById(id: number) {
  return apiFetch<InvoiceRecord>(`/billing/invoices/${id}`, {
    method: "GET",
  });
}

export async function getServiceTariffs() {
  return apiFetch<ServiceTariffRecord[]>("/billing/tariffs", {
    method: "GET",
  });
}

export async function createServiceTariff(payload: CreateServiceTariffPayload) {
  return apiFetch<ServiceTariffRecord>("/billing/tariffs", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function updateInvoiceItem(
  id: number,
  payload: UpdateInvoiceItemPayload,
) {
  return apiFetch<InvoiceRecord>(`/billing/invoice-items/${id}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function removeInvoiceItem(
  id: number,
  payload: RemoveInvoiceItemPayload,
) {
  return apiFetch<InvoiceRecord>(`/billing/invoice-items/${id}/remove`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function createCashPayment(payload: CreateCashPaymentPayload) {
  return apiFetch<PaymentRecord>("/billing/payments/cash", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export interface MpesaPaymentRequestResponse {
  message: string;
  payment: PaymentRecord;
  stkSimulation?: {
    phoneNumber: string;
    amount: number;
    checkoutRequestId: string;
    merchantRequestId: string;
  };
}

export async function createMpesaPaymentRequest(
  payload: CreateMpesaPaymentRequestPayload,
) {
  return apiFetch<MpesaPaymentRequestResponse>(
    "/billing/payments/mpesa/request",
    {
      method: "POST",
      body: JSON.stringify(payload),
    },
  );
}
export function getInvoicePdfUrl(id: number) {
  return `${API_BASE_URL}/billing/invoices/${id}/pdf`;
}
