import { apiDownload, apiFetch, API_BASE_URL } from "@/lib/api";

export interface BillingServiceItem {
  id: number;
  code: string;
  name: string;
  category?: string | null;
  defaultPrice: number;
  isActive: boolean;
}

export interface InvoiceItemRecord {
  id: number;
  invoiceId: number;
  billingServiceId?: number | null;
  description: string;
  quantity: number;
  unitPrice: number;
  discountPercent?: number;
  discountAmount?: number;
  lineTotal: number;
  statusCode: string;
  notes?: string | null;
  sourceModule?: string | null;
  sourceEntityType?: string | null;
  sourceEntityId?: string | null;
  isAutoGenerated?: boolean;
  isRemoved?: boolean;
  removedAt?: string | null;
  removedReason?: string | null;
  createdAt?: string | null;
  billingService?: {
    id: number;
    code: string;
    name: string;
    category?: string | null;
    defaultPrice: number;
  } | null;
  invoice?: InvoiceRecord;
  updatedBy?: {
    id: number;
    firstName?: string;
    lastName?: string;
    staffCode?: string;
  } | null;
}

export interface PaymentRecord {
  id: number;
  receiptNumber: string;
  invoiceId: number;
  amount: number;
  paymentMethod: string;
  statusCode: string;
  phoneNumber?: string | null;
  checkoutRequestId?: string | null;
  merchantRequestId?: string | null;
  transactionRef?: string | null;
  mpesaReceiptNumber?: string | null;
  paidAt?: string | null;
  confirmedAt?: string | null;
  notes?: string | null;
  invoice?: InvoiceRecord;
  receivedBy?: {
    id: number;
    firstName?: string;
    lastName?: string;
    staffCode?: string;
  } | null;
}

export interface InvoiceRecord {
  id: number;
  invoiceNumber: string;
  verificationCode?: string;
  statusCode: string;
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  totalAmount: number;
  paidAmount: number;
  balanceAmount: number;
  notes?: string | null;
  issuedAt?: string;
  settledAt?: string | null;
  facilityId: number;
  branchId?: number | null;
  patientId: number;
  appointmentId?: number | null;
  consultationId?: number | null;
  admissionId?: number | null;
  createdByStaffId?: number | null;
  patient?: {
    id: number;
    patientNumber?: string;
    firstName?: string;
    middleName?: string | null;
    lastName?: string;
    gender?: string | null;
    phonePrimary?: string | null;
  } | null;
  facility?: {
    id: number;
    name?: string;
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    town?: string | null;
    county?: string | null;
    country?: string | null;
    website?: string | null;
    logoUrl?: string | null;
    mpesaPaybill?: string | null;
    mpesaAccountNumber?: string | null;
    mpesaTillNumber?: string | null;
    mpesaPochiNumber?: string | null;
    mpesaShortcode?: string | null;
    showCashOnInvoice?: boolean;
    showPaybillOnInvoice?: boolean;
    showTillOnInvoice?: boolean;
    showPochiOnInvoice?: boolean;
    shaFidCode?: string | null;
  } | null;
  branch?: {
    id: number;
    name?: string;
    mpesaPaybill?: string | null;
    mpesaAccountNumber?: string | null;
    mpesaTillNumber?: string | null;
    mpesaPochiNumber?: string | null;
    mpesaShortcode?: string | null;
  } | null;
  items?: InvoiceItemRecord[];
  payments?: PaymentRecord[];
}

export interface BillingDashboardRecord {
  counts: {
    totalInvoices: number;
    pendingInvoices: number;
    partiallyPaidInvoices: number;
    paidInvoices: number;
  };
  sums: {
    totalAmount: number;
    paidAmount: number;
    balanceAmount: number;
  };
}

export interface RevenueIntegrityRecord {
  summary: {
    exceptionCount: number;
    missingPriceCount: number;
    removedLineCount: number;
    autoGeneratedCount: number;
  };
  missingPriceItems: InvoiceItemRecord[];
  removedItems: InvoiceItemRecord[];
  exceptionItems: InvoiceItemRecord[];
}

export interface CashierCloseRecord {
  date: string;
  summary: {
    paymentCount: number;
    totalCollected: number;
    invoiceCount: number;
    invoiceTotal: number;
    removedLineCount: number;
    removedLineValue: number;
    paymentsByMethod: Record<string, number>;
  };
  payments: PaymentRecord[];
  invoicesIssued: InvoiceRecord[];
  removedItems: InvoiceItemRecord[];
}

export interface ServiceTariffRecord {
  id: number;
  code: string;
  name: string;
  category: string;
  facilityId: number;
  branchId?: number | null;
  billingServiceId?: number | null;
  labTestId?: number | null;
  wardId?: number | null;
  bedId?: number | null;
  unitPrice: number;
  isActive: boolean;
  notes?: string | null;
  facility?: {
    id: number;
    name?: string;
  } | null;
  branch?: {
    id: number;
    name?: string;
  } | null;
  billingService?: {
    id: number;
    name?: string;
    code?: string;
  } | null;
  labTest?: {
    id: number;
    testName?: string;
  } | null;
  ward?: {
    id: number;
    name?: string;
  } | null;
  bed?: {
    id: number;
    bedNumber?: string;
    bedLabel?: string | null;
  } | null;
}

export interface ServiceTariffListParams {
  page?: number;
  pageSize?: number;
  search?: string;
  sortBy?: string;
  sortDirection?: "asc" | "desc";
}

export interface PaginatedServiceTariffResponse {
  data: ServiceTariffRecord[];
  meta: {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
    hasNextPage: boolean;
  };
}

export interface CreateServiceTariffPayload {
  code: string;
  name: string;
  category: string;
  facilityId: number;
  branchId?: number | null;
  billingServiceId?: number | null;
  labTestId?: number | null;
  wardId?: number | null;
  bedId?: number | null;
  unitPrice: number;
  isActive?: boolean;
  notes?: string;
}

export interface ServiceTariffTemplate {
  fileName: string;
  facilityId: number;
  branchId?: number | null;
  columns: string[];
  rowCount: number;
  csvText: string;
}

export interface ServiceTariffImportResult {
  facilityId: number;
  branchId?: number | null;
  processed: number;
  created: number;
  updated: number;
  skipped: number;
  errors: Array<{
    row: number;
    code?: string;
    message: string;
  }>;
}

export interface UpdateInvoiceItemPayload {
  description?: string;
  quantity?: number;
  unitPrice?: number;
  discountPercent?: number;
  notes?: string;
  statusCode?: string;
  updatedByStaffId?: number;
}

export interface AddInvoiceItemPayload {
  chargeType?: "SERVICE" | "LAB_TEST" | "MEDICINE" | "MANUAL";
  billingServiceId?: number;
  labTestId?: number;
  medicineId?: number;
  branchMedicineStockId?: number;
  chargedAt?: string;
  description: string;
  quantity?: number;
  unitPrice?: number;
  discountPercent?: number;
  notes?: string;
  statusCode?: string;
  updatedByStaffId?: number;
}

export interface RemoveInvoiceItemPayload {
  reason: string;
}

export interface CreateCashPaymentPayload {
  receiptNumber?: string;
  invoiceId: number;
  amount: number;
  notes?: string;
  receivedByStaffId?: number;
}

export interface CreateMpesaPaymentRequestPayload {
  receiptNumber?: string;
  invoiceId: number;
  amount: number;
  phoneNumber: string;
  notes?: string;
  receivedByStaffId?: number;
  forceResend?: boolean;
}

export interface PostAdmissionBedChargePayload {
  chargedDate?: string;
  quantity?: number;
  unitPrice?: number;
  notes?: string;
}

export interface PatientBillingWorkspace {
  patient: NonNullable<InvoiceRecord["patient"]> & {
    facilityId?: number;
  };
  openInvoice?: InvoiceRecord | null;
  invoices: InvoiceRecord[];
  activeAdmissions: Array<{
    id: number;
    statusCode?: string | null;
    admittedAt?: string | null;
    ward?: { id: number; name?: string | null } | null;
    bed?: {
      id: number;
      bedNumber?: string | null;
      bedLabel?: string | null;
    } | null;
    branch?: { id: number; name?: string | null } | null;
  }>;
  consultations: Array<{
    id: number;
    consultationNumber?: string | null;
    statusCode?: string | null;
    startedAt?: string | null;
    doctor?: {
      id: number;
      firstName?: string | null;
      lastName?: string | null;
    } | null;
  }>;
  labOrders: Array<{
    id: number;
    orderNumber?: string | null;
    status?: string | null;
    createdAt?: string | null;
    items?: Array<{
      id: number;
      status?: string | null;
      test?: { id: number; testName?: string | null } | null;
      results?: Array<{ id: number }>;
    }>;
  }>;
  prescriptions: Array<{
    id: number;
    prescriptionNumber?: string | null;
    statusCode?: string | null;
    prescribedAt?: string | null;
    items?: Array<{
      id: number;
      medicine?: { id: number; name?: string | null } | null;
    }>;
  }>;
  dispenses: Array<{
    id: number;
    dispenseNumber?: string | null;
    statusCode?: string | null;
    dispensedAt?: string | null;
    items?: Array<{
      id: number;
      quantityDispensed?: number;
      medicine?: { id: number; name?: string | null } | null;
    }>;
  }>;
  summary: {
    invoiceCount: number;
    openBalance: number;
    activeAdmissions: number;
    activeConsultations: number;
    pendingLabOrders: number;
    openPrescriptions: number;
  };
}

export async function getBillingDashboard() {
  return apiFetch<BillingDashboardRecord>("/billing/dashboard", {
    method: "GET",
  });
}

export async function getBillingServices() {
  return apiFetch<BillingServiceItem[]>("/billing/services", {
    method: "GET",
  });
}

export async function getRevenueIntegrity() {
  return apiFetch<RevenueIntegrityRecord>("/billing/revenue-integrity", {
    method: "GET",
  });
}

export async function getCashierClose(date?: string) {
  const query = date ? `?date=${encodeURIComponent(date)}` : "";
  return apiFetch<CashierCloseRecord>(`/billing/cashier-close${query}`, {
    method: "GET",
  });
}

export async function getInvoices() {
  return apiFetch<InvoiceRecord[]>("/billing/invoices", {
    method: "GET",
  });
}

export async function getInvoiceById(id: number) {
  return apiFetch<InvoiceRecord>(`/billing/invoices/${id}`, {
    method: "GET",
  });
}

export async function openPatientInvoice(
  patientId: number,
  payload: { branchId?: number; createdByStaffId?: number } = {},
) {
  return apiFetch<InvoiceRecord>(
    `/billing/patients/${patientId}/open-invoice`,
    {
      method: "POST",
      body: JSON.stringify(payload),
    },
  );
}

export async function getPatientBillingWorkspace(patientId: number) {
  return apiFetch<PatientBillingWorkspace>(
    `/billing/patients/${patientId}/workspace`,
    {
      method: "GET",
    },
  );
}

export async function getServiceTariffs(params?: ServiceTariffListParams) {
  const query = new URLSearchParams();
  if (params?.page) query.set("page", String(params.page));
  if (params?.pageSize) query.set("pageSize", String(params.pageSize));
  if (params?.search?.trim()) query.set("search", params.search.trim());
  if (params?.sortBy) query.set("sortBy", params.sortBy);
  if (params?.sortDirection) query.set("sortDirection", params.sortDirection);

  const suffix = query.toString() ? `?${query.toString()}` : "";
  return apiFetch<PaginatedServiceTariffResponse>(`/billing/tariffs${suffix}`, {
    method: "GET",
  });
}

export async function createServiceTariff(payload: CreateServiceTariffPayload) {
  return apiFetch<ServiceTariffRecord>("/billing/tariffs", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function getServiceTariffPricingTemplate(
  facilityId: number,
  branchId?: number | null,
) {
  const params = new URLSearchParams({ facilityId: String(facilityId) });
  if (branchId) {
    params.set("branchId", String(branchId));
  }

  return apiFetch<ServiceTariffTemplate>(
    `/billing/tariffs/pricing-template?${params.toString()}`,
    {
      method: "GET",
    },
  );
}

export async function importServiceTariffPricing(payload: {
  facilityId: number;
  branchId?: number | null;
  csvText: string;
}) {
  return apiFetch<ServiceTariffImportResult>(
    "/billing/tariffs/pricing-import",
    {
      method: "POST",
      body: JSON.stringify(payload),
    },
  );
}

export async function updateInvoiceItem(
  id: number,
  payload: UpdateInvoiceItemPayload,
) {
  return apiFetch<InvoiceRecord>(`/billing/invoice-items/${id}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function addInvoiceItem(
  invoiceId: number,
  payload: AddInvoiceItemPayload,
) {
  return apiFetch<InvoiceRecord>(`/billing/invoices/${invoiceId}/items`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function closeInvoice(invoiceId: number) {
  return apiFetch<InvoiceRecord>(`/billing/invoices/${invoiceId}/close`, {
    method: "POST",
  });
}

export async function removeInvoiceItem(
  id: number,
  payload: RemoveInvoiceItemPayload,
) {
  return apiFetch<InvoiceRecord>(`/billing/invoice-items/${id}/remove`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export async function postAdmissionBedCharge(
  admissionId: number,
  payload: PostAdmissionBedChargePayload,
) {
  return apiFetch<InvoiceRecord>(
    `/billing/admissions/${admissionId}/bed-charge`,
    {
      method: "POST",
      body: JSON.stringify(payload),
    },
  );
}

export async function createCashPayment(payload: CreateCashPaymentPayload) {
  return apiFetch<PaymentRecord>("/billing/payments/cash", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export interface MpesaPaymentRequestResponse {
  message: string;
  payment: PaymentRecord;
  duplicatePrevented?: boolean;
  stkRequest?: {
    phoneNumber: string;
    amount: number;
    checkoutRequestId: string;
    merchantRequestId?: string;
  };
}

export interface MpesaPaymentStatusResponse {
  message: string;
  payment: PaymentRecord;
  daraja?: Record<string, unknown> | null;
}

export async function createMpesaPaymentRequest(
  payload: CreateMpesaPaymentRequestPayload,
) {
  const normalizedPhone = payload.phoneNumber.replace(/\D/g, "");
  const idempotencyKey = [
    "mpesa",
    payload.invoiceId,
    payload.amount,
    normalizedPhone,
    Math.floor(Date.now() / 60_000),
  ].join(":");

  return apiFetch<MpesaPaymentRequestResponse>(
    "/billing/payments/mpesa/request",
    {
      method: "POST",
      headers: {
        "Idempotency-Key": idempotencyKey,
      },
      body: JSON.stringify(payload),
    },
  );
}

export async function checkMpesaPaymentStatus(checkoutRequestId: string) {
  return apiFetch<MpesaPaymentStatusResponse>(
    `/billing/payments/mpesa/status/${encodeURIComponent(checkoutRequestId)}`,
    {
      method: "GET",
    },
  );
}

export async function resendMpesaPaymentRequest(paymentId: number) {
  return apiFetch<MpesaPaymentRequestResponse>(
    `/billing/payments/${paymentId}/mpesa/resend`,
    {
      method: "POST",
    },
  );
}

export async function getPublicVerifiedInvoice(
  invoiceNumber: string,
  code: string,
) {
  const params = new URLSearchParams({ invoice: invoiceNumber, code });
  return apiFetch<InvoiceRecord>(
    `/billing-public/invoices/verify?${params.toString()}`,
    { method: "GET" },
  );
}

export function downloadPublicVerifiedInvoicePdf(
  invoiceNumber: string,
  code: string,
) {
  const params = new URLSearchParams({ invoice: invoiceNumber, code });
  return apiDownload(
    `/billing-public/invoices/verify.pdf?${params.toString()}`,
    `${invoiceNumber || "verified-invoice"}.pdf`,
  );
}
export function getInvoicePdfUrl(id: number) {
  return `${API_BASE_URL}/billing/invoices/${id}/pdf`;
}

export function downloadInvoicePdf(id: number, invoiceNumber?: string) {
  return apiDownload(
    `/billing/invoices/${id}/pdf`,
    `${invoiceNumber || `invoice-${id}`}.pdf`,
  );
}

export function downloadPaymentReceiptPdf(id: number, receiptNumber?: string) {
  return apiDownload(
    `/billing/payments/${id}/receipt.pdf`,
    `${receiptNumber || `receipt-${id}`}.pdf`,
  );
}
