CREATE TABLE `payment_adjustments` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `adjustmentNumber` VARCHAR(60) NOT NULL,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NULL,
  `invoiceId` INTEGER NOT NULL,
  `paymentId` INTEGER NOT NULL,
  `adjustmentType` VARCHAR(30) NOT NULL,
  `amount` DECIMAL(18, 2) NOT NULL,
  `reason` TEXT NOT NULL,
  `statusCode` VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
  `actorUserId` INTEGER NULL,
  `actorStaffId` INTEGER NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `payment_adjustments_adjustmentNumber_key` (`adjustmentNumber`),
  INDEX `payment_adjustments_facility_branch_created_idx` (`facilityId`, `branchId`, `createdAt`),
  INDEX `payment_adjustments_invoiceId_idx` (`invoiceId`),
  INDEX `payment_adjustments_payment_status_idx` (`paymentId`, `statusCode`),
  INDEX `payment_adjustments_actorUserId_idx` (`actorUserId`),
  INDEX `payment_adjustments_actorStaffId_idx` (`actorStaffId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `payment_adjustments_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `payment_adjustments_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `payment_adjustments_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `invoices`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `payment_adjustments_paymentId_fkey` FOREIGN KEY (`paymentId`) REFERENCES `payments`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
