import type { LucideIcon } from "lucide-react";
import {
  Ambulance,
  Baby,
  BadgeDollarSign,
  Banknote,
  BedDouble,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  Dumbbell,
  FileCheck2,
  HeartPulse,
  Microscope,
  Monitor,
  PackageCheck,
  PackageSearch,
  Pill,
  RadioTower,
  ScanLine,
  ShieldCheck,
  Stethoscope,
  Syringe,
  TabletSmartphone,
  Truck,
  Warehouse,
} from "lucide-react";

export type FacilityModule = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  accent: "cyan" | "emerald" | "amber" | "rose" | "violet";
  icon: LucideIcon;
  workflow: string[];
  records: string[];
  controls: string[];
};

export const facilityModules: FacilityModule[] = [
  {
    slug: "emergency",
    title: "Emergency Unit",
    category: "Clinical",
    summary: "Rapid arrival, triage, resuscitation, observation, and transfer control.",
    accent: "rose",
    icon: Ambulance,
    workflow: ["Arrival capture", "Triage priority", "Resus bay allocation", "Doctor handover"],
    records: ["Trauma notes", "Emergency drugs", "Observation chart", "Disposition"],
    controls: ["Priority alerts", "Bed availability", "Critical stock", "Audit trail"],
  },
  {
    slug: "radiology",
    title: "Radiology",
    category: "Diagnostics",
    summary: "Imaging requests, modality queues, reporting, and charge capture.",
    accent: "cyan",
    icon: Monitor,
    workflow: ["Request", "Schedule", "Perform scan", "Report back"],
    records: ["X-ray", "Ultrasound", "CT/MRI", "Radiologist report"],
    controls: ["Turnaround time", "Result release", "Price tariff", "Image reference"],
  },
  {
    slug: "theatre",
    title: "Theatre and Surgery",
    category: "Clinical",
    summary: "Surgical booking, pre-op checks, theatre list, procedure notes, and recovery.",
    accent: "emerald",
    icon: Syringe,
    workflow: ["Book case", "Pre-op clearance", "Theatre checklist", "Recovery handover"],
    records: ["Consent", "Anaesthesia", "Procedure note", "Implants and consumables"],
    controls: ["Theatre calendar", "Sterile stock", "Surgeon team", "Billing links"],
  },
  {
    slug: "maternity",
    title: "Maternity",
    category: "Clinical",
    summary: "ANC, labour, delivery, newborn, and postnatal care tracking.",
    accent: "rose",
    icon: Baby,
    workflow: ["ANC booking", "Labour monitoring", "Delivery record", "Postnatal review"],
    records: ["Partograph", "Newborn notes", "Maternal vitals", "Discharge plan"],
    controls: ["High-risk flags", "Birth register", "Emergency theatre", "Referral status"],
  },
  {
    slug: "dental",
    title: "Dental Clinic",
    category: "Clinical",
    summary: "Dental charting, procedures, prescriptions, and follow-up bookings.",
    accent: "cyan",
    icon: Microscope,
    workflow: ["Dental assessment", "Chart tooth", "Treat", "Review"],
    records: ["Odontogram", "Procedure plan", "Dental invoice", "Recall dates"],
    controls: ["Procedure tariffs", "Consumables", "Consent", "Clinical notes"],
  },
  {
    slug: "physiotherapy",
    title: "Physiotherapy",
    category: "Clinical",
    summary: "Therapy plans, sessions, functional scores, and progress reviews.",
    accent: "emerald",
    icon: Dumbbell,
    workflow: ["Assessment", "Care plan", "Session", "Progress review"],
    records: ["Functional score", "Treatment goals", "Session notes", "Discharge outcome"],
    controls: ["Session pricing", "Attendance", "Therapist workload", "Referral source"],
  },
  {
    slug: "nutrition",
    title: "Nutrition",
    category: "Clinical",
    summary: "Dietetic assessment, inpatient meals, supplements, and nutrition reviews.",
    accent: "amber",
    icon: HeartPulse,
    workflow: ["Screening", "Diet order", "Supplement plan", "Review"],
    records: ["BMI trends", "Diet notes", "Meal plan", "Allergy flags"],
    controls: ["Kitchen handoff", "Supplement stock", "IPD diet status", "Follow-up"],
  },
  {
    slug: "icu",
    title: "ICU and HDU",
    category: "Clinical",
    summary: "Critical care bed control, observations, ventilator data, and consultant rounds.",
    accent: "violet",
    icon: BedDouble,
    workflow: ["ICU admission", "Hourly chart", "Round", "Step-down"],
    records: ["Ventilator settings", "Fluid balance", "Medication infusion", "Care bundles"],
    controls: ["Bed-day billing", "Critical alerts", "Nurse ratio", "Isolation flag"],
  },
  {
    slug: "blood-bank",
    title: "Blood Bank",
    category: "Diagnostics",
    summary: "Blood requests, crossmatch, stock status, issue notes, and transfusion traceability.",
    accent: "rose",
    icon: ScanLine,
    workflow: ["Request blood", "Crossmatch", "Issue unit", "Transfusion close"],
    records: ["Blood group", "Unit batch", "Reaction notes", "Expiry control"],
    controls: ["Cold chain", "Compatibility", "Emergency release", "Audit log"],
  },
  {
    slug: "mortuary",
    title: "Mortuary",
    category: "Operations",
    summary: "Body admission, storage location, release approvals, and documentation.",
    accent: "violet",
    icon: FileCheck2,
    workflow: ["Receive", "Store", "Documentation", "Release"],
    records: ["Body tag", "Next of kin", "Release form", "Storage fees"],
    controls: ["Access control", "Chain of custody", "Billing", "Audit trail"],
  },
  {
    slug: "ambulance",
    title: "Ambulance and Referral",
    category: "Operations",
    summary: "Ambulance dispatch, referral notes, routes, crews, and receiving-facility handoff.",
    accent: "cyan",
    icon: RadioTower,
    workflow: ["Dispatch", "Pickup", "Clinical handoff", "Receive"],
    records: ["Crew notes", "Vitals en route", "Referral letter", "Mileage"],
    controls: ["Vehicle status", "Driver roster", "Emergency contact", "Trip billing"],
  },
  {
    slug: "cssd",
    title: "CSSD Sterilization",
    category: "Operations",
    summary: "Sterile packs, theatre trays, batch tracking, and autoclave cycle records.",
    accent: "emerald",
    icon: PackageCheck,
    workflow: ["Receive used set", "Wash", "Sterilize", "Issue sterile set"],
    records: ["Batch number", "Cycle result", "Tray contents", "Expiry"],
    controls: ["Autoclave logs", "Failed cycles", "Theatre demand", "Traceability"],
  },
  {
    slug: "infection-control",
    title: "Infection Control",
    category: "Quality",
    summary: "HAI surveillance, isolation tracking, incident review, and compliance monitoring.",
    accent: "amber",
    icon: ShieldCheck,
    workflow: ["Case flag", "Isolation", "Review", "Clearance"],
    records: ["Incident report", "Culture result", "Contact tracing", "Corrective action"],
    controls: ["Ward alerts", "Audit rounds", "Risk score", "Policy register"],
  },
  {
    slug: "insurance",
    title: "Insurance Claims",
    category: "Revenue",
    summary: "Benefit checks, pre-authorizations, claims, rejections, and payment reconciliation.",
    accent: "violet",
    icon: Banknote,
    workflow: ["Verify cover", "Authorize", "Submit claim", "Reconcile"],
    records: ["Policy details", "Claim packet", "Rejection reason", "Approval note"],
    controls: ["Payer tariffs", "Claim status", "Documents", "Credit limits"],
  },
  {
    slug: "procurement",
    title: "Procurement",
    category: "Operations",
    summary: "Purchase requests, approvals, supplier orders, receiving, and stock posting.",
    accent: "cyan",
    icon: Truck,
    workflow: ["Request", "Approve", "Order", "Receive"],
    records: ["Supplier quote", "Purchase order", "GRN", "Invoice match"],
    controls: ["Approval limits", "Lead time", "Stock impact", "Supplier score"],
  },
  {
    slug: "assets",
    title: "Assets and Maintenance",
    category: "Operations",
    summary: "Equipment register, maintenance plans, breakdowns, warranties, and lifecycle cost.",
    accent: "amber",
    icon: PackageSearch,
    workflow: ["Register", "Schedule service", "Report fault", "Close job"],
    records: ["Asset tag", "Warranty", "Service history", "Downtime"],
    controls: ["Critical asset", "Technician", "Parts", "SLA status"],
  },
  {
    slug: "biomedical",
    title: "Biomedical Engineering",
    category: "Operations",
    summary: "Medical equipment calibration, safety checks, repairs, and compliance records.",
    accent: "emerald",
    icon: Building2,
    workflow: ["Inspection", "Calibration", "Repair", "Release"],
    records: ["Calibration certificate", "Fault report", "Spare part", "Safety check"],
    controls: ["Due dates", "Risk class", "Department owner", "Downtime"],
  },
  {
    slug: "hr",
    title: "HR and Rostering",
    category: "Administration",
    summary: "Staff records, shifts, leave, call rosters, and duty coverage.",
    accent: "emerald",
    icon: BriefcaseBusiness,
    workflow: ["Staff profile", "Roster", "Attendance", "Leave"],
    records: ["Shift plan", "Contract", "Competency", "Payroll export"],
    controls: ["Role permissions", "Coverage gaps", "Approval", "Audit"],
  },
  {
    slug: "patient-portal",
    title: "Patient Portal",
    category: "Digital",
    summary: "Patient self-service for visits, invoices, results, messages, and follow-up.",
    accent: "violet",
    icon: TabletSmartphone,
    workflow: ["Verify patient", "View care", "Pay invoice", "Message facility"],
    records: ["Visit timeline", "Invoice copy", "Lab summary", "Appointment"],
    controls: ["Consent", "OTP ready", "Document access", "Secure messaging"],
  },
  {
    slug: "telemedicine",
    title: "Telemedicine",
    category: "Digital",
    summary: "Remote consultations, virtual queues, prescriptions, and follow-up notes.",
    accent: "cyan",
    icon: Stethoscope,
    workflow: ["Book virtual visit", "Join consult", "Document", "Follow-up"],
    records: ["Call status", "Clinical note", "Prescription", "Referral"],
    controls: ["Clinician availability", "Consent", "Network status", "Billing"],
  },
  {
    slug: "compliance",
    title: "Compliance and Audit",
    category: "Quality",
    summary: "Regulatory evidence, SOP controls, audit trails, and corrective actions.",
    accent: "rose",
    icon: ClipboardCheck,
    workflow: ["Audit plan", "Evidence", "Finding", "Closure"],
    records: ["Policy", "Checklist", "Incident", "CAPA"],
    controls: ["Owner", "Due date", "Risk rating", "Escalation"],
  },
  {
    slug: "revenue-integrity",
    title: "Revenue Integrity",
    category: "Revenue",
    summary: "Charge review, missing bills, cashier corrections, and daily revenue assurance.",
    accent: "amber",
    icon: BadgeDollarSign,
    workflow: ["Detect charge", "Review invoice", "Correct", "Close day"],
    records: ["Missing charge", "Removed line", "Cashier note", "Daily close"],
    controls: ["Autobill checks", "Approval", "Audit", "Exception queue"],
  },
  {
    slug: "central-store",
    title: "Central Store",
    category: "Operations",
    summary: "Common item catalogue, branch stock allocations, reorder levels, and receiving.",
    accent: "emerald",
    icon: Warehouse,
    workflow: ["Catalogue", "Receive", "Allocate", "Reorder"],
    records: ["Item master", "Batch", "Stock card", "Supplier"],
    controls: ["Branch stock", "Expiry", "Min/max", "Valuation"],
  },
  {
    slug: "pharmacy-pricing",
    title: "Pharmacy Pricing",
    category: "Revenue",
    summary: "Common medicine master with branch-specific stock, selling prices, and dispensing charges.",
    accent: "emerald",
    icon: Pill,
    workflow: ["Medicine master", "Branch price", "Dispense", "Autobill"],
    records: ["Medicine", "Branch stock", "Dispense item", "Invoice line"],
    controls: ["Reorder level", "Low stock alert", "Price override", "Audit"],
  },
];

export function getModuleBySlug(slug: string) {
  return facilityModules.find((module) => module.slug === slug);
}
