export const HMS_PERMISSIONS = [
  'patient.read',
  'patient.write',
  'billing.read',
  'billing.write',
  'payment.collect',
  'payment.manual_confirm',
  'mpesa.settings.update',
  'lab.order',
  'lab.result.enter',
  'lab.result.verify',
  'pharmacy.dispense',
  'otc.sale',
  'stock.adjust',
  'consultation.write',
  'admission.manage',
  'discharge.complete',
  'reports.read',
  'audit.read',
  'users.manage',
  'facility.manage',
  'legal.manage',
  'patient.portal.read',
  'consent.read',
  'consent.manage',
  'communication.send',
] as const;

export type HmsPermission = (typeof HMS_PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<string, HmsPermission[]> = {
  SUPER_ADMIN: [...HMS_PERMISSIONS],
  ADMIN: [...HMS_PERMISSIONS],
  FACILITY_ADMIN: [
    'patient.read',
    'patient.write',
    'billing.read',
    'billing.write',
    'payment.collect',
    'payment.manual_confirm',
    'mpesa.settings.update',
    'lab.order',
    'lab.result.enter',
    'lab.result.verify',
    'pharmacy.dispense',
    'otc.sale',
    'stock.adjust',
    'consultation.write',
    'admission.manage',
    'discharge.complete',
    'reports.read',
    'audit.read',
    'users.manage',
    'facility.manage',
    'consent.read',
    'consent.manage',
    'communication.send',
  ],
  BRANCH_ADMIN: [
    'patient.read',
    'patient.write',
    'billing.read',
    'billing.write',
    'payment.collect',
    'payment.manual_confirm',
    'lab.order',
    'lab.result.enter',
    'lab.result.verify',
    'pharmacy.dispense',
    'otc.sale',
    'stock.adjust',
    'consultation.write',
    'admission.manage',
    'discharge.complete',
    'reports.read',
    'audit.read',
    'users.manage',
    'communication.send',
  ],
  RECEPTIONIST: [
    'patient.read',
    'patient.write',
    'billing.read',
    'billing.write',
    'consent.read',
    'consent.manage',
  ],
  TRIAGE_NURSE: ['patient.read', 'consultation.write', 'consent.read'],
  NURSE: [
    'patient.read',
    'consultation.write',
    'admission.manage',
    'consent.read',
  ],
  IPD_NURSE: ['patient.read', 'consultation.write', 'admission.manage'],
  WARD_MANAGER: [
    'patient.read',
    'consultation.write',
    'admission.manage',
    'discharge.complete',
    'reports.read',
  ],
  DOCTOR: [
    'patient.read',
    'lab.order',
    'consultation.write',
    'discharge.complete',
    'consent.read',
    'consent.manage',
  ],
  CLINICIAN: [
    'patient.read',
    'lab.order',
    'consultation.write',
    'discharge.complete',
  ],
  LAB_TECHNICIAN: ['patient.read', 'lab.result.enter'],
  LAB_MANAGER: [
    'patient.read',
    'lab.result.enter',
    'lab.result.verify',
    'reports.read',
  ],
  PHARMACIST: ['patient.read', 'pharmacy.dispense', 'otc.sale', 'billing.read'],
  PHARMACY_MANAGER: [
    'patient.read',
    'pharmacy.dispense',
    'otc.sale',
    'stock.adjust',
    'billing.read',
    'reports.read',
  ],
  CASHIER: [
    'patient.read',
    'billing.read',
    'billing.write',
    'payment.collect',
    'otc.sale',
  ],
  BILLING_OFFICER: [
    'patient.read',
    'billing.read',
    'billing.write',
    'payment.collect',
    'otc.sale',
    'reports.read',
  ],
  INVENTORY_OFFICER: ['stock.adjust', 'reports.read'],
  REPORTS_MANAGER: ['reports.read'],
  AUDITOR: ['audit.read', 'reports.read'],
  PATIENT: ['patient.portal.read'],
};

export function roleHasPermission(
  roleCode: string | null | undefined,
  permission: HmsPermission,
) {
  if (!roleCode) return false;
  return Boolean(ROLE_PERMISSIONS[roleCode]?.includes(permission));
}

export function roleHasEveryPermission(
  roleCode: string | null | undefined,
  permissions: HmsPermission[],
) {
  return permissions.every((permission) =>
    roleHasPermission(roleCode, permission),
  );
}
