CREATE TABLE `external_lab_referrals` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `referralNumber` VARCHAR(60) NOT NULL,
  `facilityId` INTEGER NOT NULL,
  `branchId` INTEGER NULL,
  `referringFacilityName` VARCHAR(200) NOT NULL,
  `referringFacilityContact` VARCHAR(120) NULL,
  `referringClinicianName` VARCHAR(180) NULL,
  `externalPatientName` VARCHAR(200) NOT NULL,
  `externalPatientIdentifier` VARCHAR(120) NULL,
  `patientPhone` VARCHAR(30) NULL,
  `patientEmail` VARCHAR(255) NULL,
  `sampleReference` VARCHAR(100) NOT NULL,
  `specimenType` VARCHAR(100) NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `receivedByStaffId` INTEGER NULL,
  `clinicalNotes` TEXT NULL,
  `urgency` VARCHAR(30) NOT NULL DEFAULT 'ROUTINE',
  `statusCode` VARCHAR(40) NOT NULL DEFAULT 'RECEIVED',
  `billingCategory` VARCHAR(40) NOT NULL DEFAULT 'EXTERNAL',
  `billingStatus` VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `external_lab_referrals_referralNumber_key` (`referralNumber`),
  INDEX `external_lab_referrals_facility_branch_status_received_idx` (`facilityId`, `branchId`, `statusCode`, `receivedAt`),
  INDEX `external_lab_referrals_referringFacilityName_idx` (`referringFacilityName`),
  INDEX `external_lab_referrals_sampleReference_idx` (`sampleReference`),
  INDEX `external_lab_referrals_externalPatientIdentifier_idx` (`externalPatientIdentifier`),
  PRIMARY KEY (`id`),
  CONSTRAINT `external_lab_referrals_facilityId_fkey` FOREIGN KEY (`facilityId`) REFERENCES `facilities`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `external_lab_referrals_branchId_fkey` FOREIGN KEY (`branchId`) REFERENCES `branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `external_lab_order_items` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `externalLabReferralId` INTEGER NOT NULL,
  `testId` INTEGER NOT NULL,
  `instructions` TEXT NULL,
  `statusCode` VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  `priceAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `external_lab_order_items_referralId_idx` (`externalLabReferralId`),
  INDEX `external_lab_order_items_testId_idx` (`testId`),
  INDEX `external_lab_order_items_statusCode_idx` (`statusCode`),
  PRIMARY KEY (`id`),
  CONSTRAINT `external_lab_order_items_referralId_fkey` FOREIGN KEY (`externalLabReferralId`) REFERENCES `external_lab_referrals`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `external_lab_order_items_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `lab_test_catalog`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `external_lab_results` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `externalLabOrderItemId` INTEGER NOT NULL,
  `resultValue` TEXT NOT NULL,
  `remarks` TEXT NULL,
  `recordedByStaffId` INTEGER NULL,
  `recordedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `statusCode` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  `validatedByStaffId` INTEGER NULL,
  `validatedAt` DATETIME(3) NULL,
  `validationNotes` TEXT NULL,
  `releasedByStaffId` INTEGER NULL,
  `releasedAt` DATETIME(3) NULL,
  `signatureHash` VARCHAR(128) NULL,
  UNIQUE INDEX `external_lab_results_orderItemId_key` (`externalLabOrderItemId`),
  INDEX `external_lab_results_status_validated_idx` (`statusCode`, `validatedAt`),
  INDEX `external_lab_results_releasedAt_idx` (`releasedAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `external_lab_results_orderItemId_fkey` FOREIGN KEY (`externalLabOrderItemId`) REFERENCES `external_lab_order_items`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
